name: Packet Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/azure-cli.list
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm -f /etc/apt/sources.list.d/azure-cli.sources
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.sources
        sudo apt-get update || true
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install --with-deps
    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:.:api
        pytest
